[files]
# Milking Parlor Log
parlor_log = C:\Program Files\Afimilk\Logs\RTC\MILKINGPARLOR\RTC_MILKINGPARLOR.log
# ID to EID CSV
eid_map_csv = D:\Study\Freelancing\Gary\cow-processor-log\map.csv

[processing]
# Milking Parlor Log check interval (seconds)
parlor_interval = 3

# Milking Parlor Stalls
parlor_stalls = 114

# Transmit offset (number of stalls to wait before transmitting)
transmit_offset = 60

[network]
# RevPi connection details
revpi_host = 192.168.1.100
revpi_port = 8080

[logging]
# Logging configuration
level = INFO
file = log2.log
max_size_mb = 10
backup_count = 5

[output]
; mode = revpi
mode = csv
csv_file = transmit_output2.csv